### ISSUE TITLE
/mreact trigger-role working only on reaction add

### ISSUE THREAD

**Issue by KGS501** [Maveo/Spark#31]
Spark has an issue, where a /mreact trigger-role reaction is given and removed only if a user reacts to a message. The proper function of this command would be to give a role to the user when he reacts to the message and remove the role, when he removes his reaction, not to perform both actions when he reacts to the message.
The reaction under the message should function more like a switch, not like a button.

**Comment by KGS501** [comment]
### Issued Behaviour

1. Add `/mreact trigger-role` reaction to message
2. Press the reaction emoji
3. You get the stated role
4. Press the reaction emoji again, removing your reaction
5. You don't lose your role
6. Press the reaction emoji again, adding your reaction again
7. You loose the stated role

### Expected Behaviour

1. Add `/mreact trigger-role` reaction to message
2. Press the reaction emoji
3. You get the stated role
4. Press the reaction emoji again, removing your reaction
5. You lose the stated role

**Comment by skillor** [comment]
fix: a3a1bb81efaebb40d36599c72554183bf10671f3
