### ISSUE TITLE
Manage multiple message-reaction actions on one reaction-emoji

### ISSUE THREAD

**Issue by KGS501** [Maveo/Spark#33]
**Detailed Description**

Spark should be able to manage multiple reaction actions on a single reaction-emoji. Due to a bug it is currently possible to assign multiple different actions to a single reaction-emoji, which is a really helpful feature, but since this behavior was not intended to happen in the first place, Spark is not able to manage multiple reaction-actions on a single reaction-emoji very well.

**Solution**

Like multiple reaction-actions on **different** reaction-emojis, Admins should have the ability to delete individual reaction-actions and not delete only a whole reaction-emoji which might be assigned with multiple different actions. For this to work, the `/mreact remove` command must distinquish between not only message-id, reaction-emoji but additionally between action-type, and the corresponding id, so Admins can remove individual actions (toggle-role, dm, etc.) from a single emoji.

**Example**

`/mreact remove {message-id} {emoji} {action-type} {action-content}`

In this example a single message (messsage-id: 203457263402734) with a single reaction-emoji (😀) has two actions assigned to it. "toggle-role" (role-id: 8560578629348010) and "dm" (dm content: This is the content of the dm message. Thank you for clicking on the emoji.). The user will receive a dm from the bot and be assigned a role, when clicking on the reaction-emoji. To remove individual reaction-actions from the same reaction-emoji admins would use the following two commands.

`/mreact remove 203457263402734 😀 toggle-role 8560578629348010`
`/mreact remove 203457263402734 😀 dm This is the content of the dm message. Thank you for clicking on the emoji.`

**Important Notice**

If possible the current method of removing whole reaction emojis without differentiating between multiple reaction-actions (`/mreact remove 203457263402734 😀`) should be kept as it will allow for quicker removal of single-assigned reaction-emojis and will allow admins to still delete a whole reaction-emoji at once, even if assigned with multiple reaction-action if neccessary.

**Comment by skillor** [comment]
![image](https://user-images.githubusercontent.com/10564224/159142714-33ab3fe3-969c-4acf-a6e2-d99cb336429f.png)
