### ISSUE TITLE
Super Admin status error

### ISSUE THREAD

**Issue by KGS501** [Maveo/Spark#46]
### Describe the Bug

I get an error when setting Sparks status to anything else than "playing" in the Super Admin Tab. After changing the status activity in the dropdown, Sparks status can't be set until you refresh the website and then don't change his status activity.

### To Reproduce

1. Navigate to Super Admin in Sparks Web Client
2. change the dropdown from "playing" to something else
3. Enter anything in the status text box
4. Click send

### Expected behaviour

I expected all dropdown items to work.

### Screenshots

![image](https://user-images.githubusercontent.com/83352171/159734042-80c50dc0-567e-42c0-a602-1c2fa7d608f6.png)

**Comment by skillor** [comment]
30ab856f6b41eadf23646fa91062766f111c18b6
