### ISSUE TITLE
Custom Profile Cards

### ISSUE THREAD

**Issue by KGS501** [Maveo/Spark#49]
### Description

Spark should be able to create profile cards with configurable variables. This feature would be used in combination with the inventory system to create items, which contain profile card components like custom emojis, titles, custom backgrounds and can be equipped by the user to alter the appearance of their profile card. 

### Example situation

1. A member uses an item, which adds a title beneath their name on the profile card
2. The member then uses another item, that changes the background of their profile cards
3. The profile card then contains both changes and can be viewed on the web client and discord

### Additional context

The feature would be implemented with unique identifier in the [imagestack-svg](https://github.com/skillor/imagestack-svg-python) code to ensure that all changes and all items can be combined with each other.

**Comment by skillor** [comment]
ab9172e1758aa51d5790ad6921212f5e3ad4dede
