### ISSUE TITLE
Ranking page fails to load when role doesn't start with an emoji

### ISSUE THREAD

**Issue by dreiekk** [Maveo/Spark#56]
### Describe the Bug

Ranking page fails to load with an `400 Bad request` error when a user has a top role, that doesn't start with an emoji in it's name.
I suspect ImageStack can't generate the final image without an emoji and throws an error.
```json
{
    "code": 400,
    "description": "a bytes-like object is required, not 'NoneType'",
    "name": "TypeError"
}
```

### To Reproduce

1. Create a testrole with a name, that doesn't start with a emoji.
2. Assign it as the top role to a user. 
3. Open up the ranking page in the web frontend.
4. ...
5. Profit?

### Expected behaviour

Don't fail to load the page completely. Show an error or replace the missing emoji with a placeholder image.

### Screenshots

![grafik](https://user-images.githubusercontent.com/25348281/163867148-718680ef-dda2-403c-84a3-d92b84ff91ce.png)

**Comment by skillor** [comment]
a6193014252a1def037bbccb274314e60e2ec7ca
