### ISSUE TITLE
Settings page won't load certain image previews due to roles not starting with an emoji

### ISSUE THREAD

**Issue by dreiekk** [Maveo/Spark#57]
### Describe the Bug

Image previews from LEVEL_UP_IMAGE, PROFILE_IMAGE, RANKING_IMAGE and WELCOME_IMAGE fail to load with an 400 Bad request error when it tries to generate an image from a role, that doesn't start with an emoji in it's name.
I suspect ImageStack can't generate the final image without an emoji and throws an error.
```json
{
    "code": 400,
    "description": "a bytes-like object is required, not 'NoneType'",
    "name": "TypeError"
}
```

### Expected behaviour

Don't fail to load the page completely. Show an error or replace the missing emoji with a placeholder image.

### Screenshots

![grafik](https://user-images.githubusercontent.com/25348281/163868144-5498ff7b-b744-43b3-a465-72707692fcb4.png)

**Comment by dreiekk** [comment]
@skillor Don't think too much about the scuffed sidebar in the screenshot. It's how firefox makes full-height website screenshots...

**Comment by skillor** [comment]
a6193014252a1def037bbccb274314e60e2ec7ca
