### ISSUE TITLE
Wheelspin without any prizes results in "list index out of range"

### ISSUE THREAD

**Issue by dreiekk** [Maveo/Spark#59]
### Describe the Bug

When you try to spin the wheel without any prizes configured, an error message `list index out of range` shows up.

### To Reproduce

1. Don't configure any wheelspin prizes.
2. Wheelspin

### Expected behaviour

Catch the error and display a custom message.

### Screenshots

![grafik](https://user-images.githubusercontent.com/25348281/163870657-64cfd6d1-b06e-4869-8cfd-074458015800.png)

**Comment by skillor** [comment]
baa6f1a6dda99f6cb9eda8816c6655524c04ca6b
