### ISSUE TITLE
Userfriendly Error message: No direct message possible

### ISSUE THREAD

**Issue by KGS501** [Maveo/Spark#63]
### Describe the Bug

If a user hasn't enabled the "allow direct messages from server members" setting, Spark is not able to send users direct messages when creating a promo code. Spark currently gives out a cryptic error message, which is hard to interpret for regular users.

### To Reproduce

Use an account, which has not interacted with Spark before

1. Go to _user settings_ -> _Privacy & Safety_
2. Disable "**allow direct messages from server members**" under _server privacy defaults_
3. Use the `/promo` command

### Expected behaviour

Spark should give an easy-to-understand explanation of what went wrong and what the user has to do to recieve the direct message in the server text-channel in which the command was used.

### Screenshots

![image](https://user-images.githubusercontent.com/83352171/167457674-84de20fb-3458-445d-b86f-42b36823d360.png)

**Comment by skillor** [comment]
I checked the use-case ```/promo``` and the send dm emoji reaction. Anywhere else this could be relevant? @KGS501

**Comment by KGS501** [comment]
Potentially anytime Spark tries to send a direct message to a user with this disabled setting. Message reactions can be configured to send dms aswell and other future use cases

**Comment by skillor** [comment]
> Potentially anytime Spark tries to send a direct message to a user with this disabled setting. Message reactions can be configured to send dms aswell and other future use cases

No they can not. And I can't fix the future lol

**Comment by KGS501** [comment]
emoji-reaction*
