### ISSUE TITLE
Kicking/Deleting user after promo boost leads to error

### ISSUE THREAD

**Issue by KGS501** [Maveo/Spark#66]
### Describe the Bug

After a user account, which is currently boosting another user is deleted from discord and kicked from the server, the profile card from the user, which has been boosted by the deleted user can no longer by shown in discord chat.

(The user which received the boosts can furthermore no longer access the spark-web-client and is stuck in an infinite loading screen)

### To Reproduce

1. New user enters a promo code from existing user
2. New user boosts existing user with `/boost `
3. New user account is deleted from discord
4. New user is kicked from the server
5. Old users profile card cannot be shown in discord chat when using `/profile OldUser`

### Expected behaviour

No errors should be caused by a user being deleted and/or kicked while still boosting someone.

### Screenshots

![image](https://user-images.githubusercontent.com/83352171/170880029-8fcc30da-f4d5-4d44-93e3-5726e9616151.png)

**Comment by skillor** [comment]
b6538ba64d280e13f27aa28a0acf27177a0fc74e
